#!/usr/bin/env python3
"""Render the Felix .config templates and the backend metadata for the lab.

    python scripts/lab_config.py render [--force]
    python scripts/lab_config.py show

Reads energy/infra/config/<service>/... (templates with ${PLACEHOLDER}
tokens), writes energy/infra/runtime/<service>/config/... plus
runtime/backend/metadata.json and energy/infra/.env. The .env carries the
generated Influx admin token and edge apikey and is git-ignored.

Both secrets are lab-only random strings; they are generated once and reused
on later renders unless --force is given.
"""
from __future__ import annotations

import argparse
import json
import re
import secrets
import shutil
import sys
from pathlib import Path
from string import Template

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lab_common import (  # noqa: E402
    ENV_FILE, INFRA_DIR, LabError, RUNTIME_DIR, read_env_file, write_json,
)

TEMPLATE_DIR = INFRA_DIR / "config"
SERVICES = ("backend", "backend-edge", "edge")
PLACEHOLDER = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")

# Fixed lab topology. Ports are the ones recorded in docs/03-architecture.md.
DEFAULTS = {
    "EDGE_ID": "edge0",
    "EDGE_FELIX_PORT": "8080",
    "EDGE_REST_PORT": "8084",
    "EDGE_BACKEND_URI": "ws://relay:18081",
    "BACKEND_FELIX_PORT": "8079",
    "BACKEND_EDGE_MANAGER_PORT": "8083",
    "BACKEND_METADATA_PATH": "/var/opt/openems/metadata.json",
    "BACKEND_EDGE_FELIX_PORT": "8078",
    "BACKEND_EDGE_APP_PORT": "8081",
    "BACKEND_EDGE_APP_URI": "ws://backend:8083",
    "INFLUX_URL": "http://influx:8086",
    "INFLUX_ORG": "openems",
    "INFLUX_BUCKET": "openems",
    "INFLUX_MEASUREMENT": "data",
    "INFLUX_USERNAME": "lab",
    "ESS_CAPACITY_WH": "10200",
    "ESS_MAX_APPARENT_POWER_VA": "10000",
    "ESS_MAX_CHARGE_W": "10000",
    "ESS_MAX_DISCHARGE_W": "10000",
    "ESS_INITIAL_SOC_PCT": "50",
}
SECRET_KEYS = ("INFLUX_TOKEN", "INFLUX_PASSWORD", "EDGE_APIKEY")


def generate_secret(nbytes: int = 24) -> str:
    return secrets.token_urlsafe(nbytes)


def lab_values(existing: dict | None = None, force: bool = False, overrides: dict | None = None) -> dict:
    """Merge defaults, previously generated secrets and explicit overrides."""
    values = dict(DEFAULTS)
    existing = existing or {}
    for key in SECRET_KEYS:
        if not force and existing.get(key):
            values[key] = existing[key]
        else:
            values[key] = generate_secret()
    for key, value in existing.items():
        if key not in SECRET_KEYS and key in DEFAULTS:
            values[key] = value
    if overrides:
        values.update({k: str(v) for k, v in overrides.items()})
    return values


def render_text(template: str, values: dict, source: str = "<template>") -> str:
    """Substitute ${NAME} tokens; unknown tokens are an error, never left behind."""
    missing = sorted({m.group(1) for m in PLACEHOLDER.finditer(template)} - set(values))
    if missing:
        raise LabError(f"{source}: no value for placeholder(s) {', '.join(missing)}")
    rendered = Template(template).substitute(values)
    if "${" in rendered:
        raise LabError(f"{source}: unresolved placeholder remains after rendering")
    return rendered


def render_tree(template_root: Path, output_root: Path, values: dict) -> list:
    """Render every *.config under template_root into output_root; return written paths."""
    if not template_root.is_dir():
        raise LabError(f"template directory missing: {template_root}")
    if output_root.exists():
        shutil.rmtree(output_root)
    written = []
    for source in sorted(template_root.rglob("*.config")):
        relative = source.relative_to(template_root)
        target = output_root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        text = render_text(source.read_text(encoding="utf-8"), values, str(relative))
        with target.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        written.append(target)
    if not written:
        raise LabError(f"no .config templates found under {template_root}")
    return written


def metadata_document(values: dict) -> dict:
    """Metadata.File document: one edge whose apikey is the generated lab key."""
    return {
        "edges": {
            values["EDGE_ID"]: {
                "apikey": values["EDGE_APIKEY"],
                "setuppassword": values["EDGE_APIKEY"],
                "comment": "P02 lab edge (generated, non-secret lab key)",
            }
        }
    }


def env_text(values: dict) -> str:
    lines = ["# Generated by scripts/lab_config.py. Git-ignored: contains lab secrets."]
    for key in sorted(values):
        lines.append(f"{key}={values[key]}")
    return "\n".join(lines) + "\n"


def render_all(template_dir: Path = TEMPLATE_DIR, runtime_dir: Path = RUNTIME_DIR,
               env_file: Path = ENV_FILE, force: bool = False, overrides: dict | None = None) -> dict:
    values = lab_values(read_env_file(env_file), force=force, overrides=overrides)
    written = {}
    for service in SERVICES:
        files = render_tree(template_dir / service, runtime_dir / service / "config", values)
        (runtime_dir / service / "data").mkdir(parents=True, exist_ok=True)
        written[service] = [p.as_posix() for p in files]
    metadata_path = runtime_dir / "backend" / "metadata.json"
    write_json(metadata_path, metadata_document(values))
    written["metadata"] = metadata_path.as_posix()
    env_file.parent.mkdir(parents=True, exist_ok=True)
    with env_file.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(env_text(values))
    written["env"] = env_file.as_posix()
    return {"values": values, "written": written}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    render = sub.add_parser("render", help="Render runtime configs, metadata.json and .env.")
    render.add_argument("--force", action="store_true", help="Regenerate secrets even if .env exists.")
    sub.add_parser("show", help="Print the non-secret lab values.")
    args = parser.parse_args(argv)

    try:
        if args.command == "render":
            result = render_all(force=args.force)
            count = sum(len(v) for v in result["written"].values() if isinstance(v, list))
            print(f"RENDERED {count} config files under {RUNTIME_DIR}")
            print(f"metadata: {result['written']['metadata']}")
            print(f"env:      {result['written']['env']}  (git-ignored)")
            return 0
        values = lab_values(read_env_file(ENV_FILE))
        print(json.dumps({k: v for k, v in values.items() if k not in SECRET_KEYS}, indent=2))
        return 0
    except LabError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
